{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "81a2bbcb-5bba-4f7d-9634-0bc21f64974a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: streamlit in c:\\users\\guilh\\anaconda3\\lib\\site-packages (1.45.1)\n",
      "Collecting streamlit-timeline\n",
      "  Downloading streamlit-timeline-0.0.2.tar.gz (2.9 kB)\n",
      "  Preparing metadata (setup.py): started\n",
      "  Preparing metadata (setup.py): finished with status 'done'\n",
      "Requirement already satisfied: altair<6,>=4.0 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from streamlit) (5.5.0)\n",
      "Requirement already satisfied: blinker<2,>=1.5.0 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from streamlit) (1.9.0)\n",
      "Requirement already satisfied: cachetools<6,>=4.0 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from streamlit) (5.5.1)\n",
      "Requirement already satisfied: click<9,>=7.0 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from streamlit) (8.1.8)\n",
      "Requirement already satisfied: numpy<3,>=1.23 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from streamlit) (2.1.3)\n",
      "Requirement already satisfied: packaging<25,>=20 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from streamlit) (24.2)\n",
      "Requirement already satisfied: pandas<3,>=1.4.0 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from streamlit) (2.2.3)\n",
      "Requirement already satisfied: pillow<12,>=7.1.0 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from streamlit) (11.1.0)\n",
      "Requirement already satisfied: protobuf<7,>=3.20 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from streamlit) (5.29.3)\n",
      "Requirement already satisfied: pyarrow>=7.0 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from streamlit) (19.0.0)\n",
      "Requirement already satisfied: requests<3,>=2.27 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from streamlit) (2.32.3)\n",
      "Requirement already satisfied: tenacity<10,>=8.1.0 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from streamlit) (9.0.0)\n",
      "Requirement already satisfied: toml<2,>=0.10.1 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from streamlit) (0.10.2)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from streamlit) (4.12.2)\n",
      "Requirement already satisfied: watchdog<7,>=2.1.5 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from streamlit) (4.0.2)\n",
      "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from streamlit) (3.1.43)\n",
      "Requirement already satisfied: tornado<7,>=6.0.3 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from streamlit) (6.5.1)\n",
      "Requirement already satisfied: jinja2 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (3.1.6)\n",
      "Requirement already satisfied: jsonschema>=3.0 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (4.23.0)\n",
      "Requirement already satisfied: narwhals>=1.14.2 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (1.31.0)\n",
      "Requirement already satisfied: colorama in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from click<9,>=7.0->streamlit) (0.4.6)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)\n",
      "Requirement already satisfied: smmap<5,>=3.0.1 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from pandas<3,>=1.4.0->streamlit) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2.3.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2025.11.12)\n",
      "Requirement already satisfied: attrs>=22.2.0 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (24.3.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.22.3)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\users\\guilh\\anaconda3\\lib\\site-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.2)\n",
      "Building wheels for collected packages: streamlit-timeline\n",
      "  Building wheel for streamlit-timeline (setup.py): started\n",
      "  Building wheel for streamlit-timeline (setup.py): finished with status 'done'\n",
      "  Created wheel for streamlit-timeline: filename=streamlit_timeline-0.0.2-py3-none-any.whl size=2768 sha256=c49cfbda4720d705cde7c4ab14b95336205027c3e1f0af6aa6a820422a33a6eb\n",
      "  Stored in directory: c:\\users\\guilh\\appdata\\local\\pip\\cache\\wheels\\a9\\9d\\39\\5b9e615ac468f99bc0505e826a066a051a7f189a4805c0c6b8\n",
      "Successfully built streamlit-timeline\n",
      "Installing collected packages: streamlit-timeline\n",
      "Successfully installed streamlit-timeline-0.0.2\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  DEPRECATION: Building 'streamlit-timeline' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'streamlit-timeline'. Discussion can be found at https://github.com/pypa/pip/issues/6334\n"
     ]
    }
   ],
   "source": [
    "pip install streamlit streamlit-timeline"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "74301a72-0337-4340-a118-bff9ffd8075d",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-03-13 20:35:50.035 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-13 20:35:50.036 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-13 20:35:50.739 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\Guilh\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-03-13 20:35:50.739 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-13 20:35:50.741 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-13 20:35:50.743 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-13 20:35:50.745 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-13 20:35:50.746 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-13 20:35:50.754 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-13 20:35:50.847 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-13 20:35:50.848 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-13 20:35:50.851 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-13 20:35:50.855 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-13 20:35:50.857 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-13 20:35:50.858 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-13 20:35:50.860 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-13 20:35:50.862 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-13 20:35:50.862 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-13 20:35:50.864 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-13 20:35:50.867 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-13 20:35:50.872 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "from streamlit_timeline import timeline\n",
    "\n",
    "# Page setup for a professional look\n",
    "st.set_page_config(\n",
    "    page_title=\"Guilherme Oyakawa - Professional Journey\", \n",
    "    page_icon=\"📊\", \n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "st.title(\"📂 Professional & Personal Timeline\")\n",
    "st.subheader(\"Guilherme Oyakawa de Almeida | Data & Business Analyst\")\n",
    "\n",
    "# Data structure containing your life events\n",
    "# Comments in English to maintain the coding standard\n",
    "items = {\n",
    "    \"events\": [\n",
    "        {\n",
    "            \"start_date\": {\"year\": \"1994\", \"month\": \"1\", \"day\": \"27\"},\n",
    "            \"text\": {\n",
    "                \"headline\": \"👶 Born in Santo André, Brazil\",\n",
    "                \"text\": \"The start of the journey in São Paulo state.\"\n",
    "            }\n",
    "        },\n",
    "        {\n",
    "            \"start_date\": {\"year\": \"1998\", \"month\": \"8\"},\n",
    "            \"end_date\": {\"year\": \"2000\", \"month\": \"1\"},\n",
    "            \"text\": {\n",
    "                \"headline\": \"🇩🇪 First International Experience\",\n",
    "                \"text\": \"Moved to Germany for the first time, beginning a life of multicultural experiences.\"\n",
    "            }\n",
    "        },\n",
    "        {\n",
    "            \"start_date\": {\"year\": \"2009\", \"month\": \"3\"},\n",
    "            \"end_date\": {\"year\": \"2011\", \"month\": \"6\"},\n",
    "            \"text\": {\n",
    "                \"headline\": \"🇩🇪 Education in Germany\",\n",
    "                \"text\": \"Second experience in Germany, attending Realschule and Gymnasium, strengthening European cultural ties.\"\n",
    "            }\n",
    "        },\n",
    "        {\n",
    "            \"start_date\": {\"year\": \"2012\", \"month\": \"2\"},\n",
    "            \"text\": {\n",
    "                \"headline\": \"⚙️ First Job: Engineering Intern\",\n",
    "                \"text\": \"<b>Rucker do Brasil:</b> Developed technical drawing skills using Catia V5 for major clients like Peugeot, Volkswagen, and Renault.\"\n",
    "            }\n",
    "        },\n",
    "        {\n",
    "            \"start_date\": {\"year\": \"2016\", \"month\": \"7\"},\n",
    "            \"text\": {\n",
    "                \"headline\": \"🍦 Store Manager - Family Business\",\n",
    "                \"text\": \"Managed operations, inventory, and financial control, optimizing cash flow and customer experience.\"\n",
    "            }\n",
    "        },\n",
    "        {\n",
    "            \"start_date\": {\"year\": \"2017\", \"month\": \"1\"},\n",
    "            \"text\": {\n",
    "                \"headline\": \"🎓 Business Management Degree\",\n",
    "                \"text\": \"Enrolled at Faculdade São Bernardo (FASB) to solidify business foundations.\"\n",
    "            }\n",
    "        },\n",
    "        {\n",
    "            \"start_date\": {\"year\": \"2019\", \"month\": \"10\"},\n",
    "            \"text\": {\n",
    "                \"headline\": \"🌐 Intern at T-Systems do Brasil\",\n",
    "                \"text\": \"Assisted Service Delivery Managers (SDMs) and conducted daily meetings with global teams in English.\"\n",
    "            }\n",
    "        },\n",
    "        {\n",
    "            \"start_date\": {\"year\": \"2022\", \"month\": \"3\"},\n",
    "            \"text\": {\n",
    "                \"headline\": \"📦 Business Assistant at Zenatur\",\n",
    "                \"text\": \"Coordinated logistics for Samsung promotional materials at major events like Brasil Game Show (BGS).\"\n",
    "            }\n",
    "        },\n",
    "        {\n",
    "            \"start_date\": {\"year\": \"2022\", \"month\": \"10\", \"day\": \"28\"},\n",
    "            \"text\": {\n",
    "                \"headline\": \"🕯️ Personal Loss\",\n",
    "                \"text\": \"Passing of my mother. A moment of profound personal transformation and resilience.\"\n",
    "            }\n",
    "        },\n",
    "        {\n",
    "            \"start_date\": {\"year\": \"2023\", \"month\": \"4\"},\n",
    "            \"text\": {\n",
    "                \"headline\": \"🇮🇹 Move to Italy\",\n",
    "                \"text\": \"Relocated to Italy to seek new professional horizons in the European market.\"\n",
    "            }\n",
    "        },\n",
    "        {\n",
    "            \"start_date\": {\"year\": \"2023\", \"month\": \"8\"},\n",
    "            \"text\": {\n",
    "                \"headline\": \"🏎️ Consultant at Micla Engineering\",\n",
    "                \"text\": \"Supported <b>Italdesign Giugiaro</b> in automotive durability testing and process improvement.\"\n",
    "            }\n",
    "        },\n",
    "        {\n",
    "            \"start_date\": {\"year\": \"2023\", \"month\": \"10\"},\n",
    "            \"text\": {\n",
    "                \"headline\": \"📈 Master in Data Science\",\n",
    "                \"text\": \"Enrolled at Rome Business School to transition into advanced data analytics.\"\n",
    "            }\n",
    "        },\n",
    "        {\n",
    "            \"start_date\": {\"year\": \"2024\", \"month\": \"10\"},\n",
    "            \"text\": {\n",
    "                \"headline\": \"🎓 Master's Degree Completed\",\n",
    "                \"text\": \"Finished Master in Data Science with a high grade of 28/30.\"\n",
    "            }\n",
    "        },\n",
    "        {\n",
    "            \"start_date\": {\"year\": \"2025\", \"month\": \"5\"},\n",
    "            \"text\": {\n",
    "                \"headline\": \"🇪🇺 Portuguese Citizenship\",\n",
    "                \"text\": \"Dual citizenship granted, enabling full work authorization across the European Union.\"\n",
    "            }\n",
    "        },\n",
    "        {\n",
    "            \"start_date\": {\"year\": \"2025\", \"month\": \"7\"},\n",
    "            \"text\": {\n",
    "                \"headline\": \"🛠️ Quality Operator at Coveract\",\n",
    "                \"text\": \"Worked at Minibea Access Solutions for <b>BMW</b>, analyzing performance charts and ensuring quality standards.\"\n",
    "            }\n",
    "        },\n",
    "        {\n",
    "            \"start_date\": {\"year\": \"2025\", \"month\": \"10\"},\n",
    "            \"text\": {\n",
    "                \"headline\": \"📜 Professional Certificate - Imperial College\",\n",
    "                \"text\": \"Specializing in Data Analytics at Imperial College Business School.\"\n",
    "            }\n",
    "        },\n",
    "        {\n",
    "            \"start_date\": {\"year\": \"2026\"},\n",
    "            \"text\": {\n",
    "                \"headline\": \"🚀 The New Phase\",\n",
    "                \"text\": \"Looking forward to new challenges as a Data Analyst in Europe!\"\n",
    "            }\n",
    "        }\n",
    "    ]\n",
    "}\n",
    "\n",
    "# Render the timeline component\n",
    "timeline(items, height=700)\n",
    "\n",
    "# Sidebar for quick facts\n",
    "with st.sidebar:\n",
    "    st.image(\"https://img.icons8.com/clouds/100/data-configuration.png\")\n",
    "    st.header(\"Key Information\")\n",
    "    st.write(\"**Full Name:** Guilherme Oyakawa de Almeida\")\n",
    "    st.write(\"**Languages:** Portuguese, English, German\")\n",
    "    st.write(\"**Citzenship:** Brazilian & Portuguese\")\n",
    "    st.write(\"**Top Skills:** Python, SQL, Power BI, Data Science\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ac0b176b-ed3a-457c-81be-a079ff05bd5a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
